### ISSUE TITLE
Error: Section 'axis_twist_compensation' is not a valid config section [BUG] 

### ISSUE THREAD

**Issue by JoopVerdoorn** [bassamanator/Sovol-SV06-firmware#118]
**Describe the bug**
=======================
After installing Mainsail OS, emptying the ~/printer_data/config folder, using the git-method for retrieving and installing the SV06-plus configuration, determin the path of my printer and adding a line that in the printer.cfg of the MCU restarting the firmware gives this error in klippy.log:
`[filament_switch_sensor filament_sensor]
switch_pin = PA4
pause_on_runout = True
insert_gcode = 
	{ action_respond_info("Insert Detected") }
runout_gcode = 
	{ action_respond_info("Runout Detected") }
	CONDITIONAL_BEEP i=3 dur=300 freq=400
Extruder max_extrude_ratio=2.078758
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 145, in _read_config
    pconfig.check_unused_options(config)
  File "/home/pi/klipper/klippy/configfile.py", line 299, in check_unused_options
    raise error("Section '%s' is not a valid config section"
configparser.Error: Section 'axis_twist_compensation' is not a valid config section
webhooks client 4130828688: New connection
webhooks client 4130828688: Client info {'program': 'Moonraker', 'version': 'v0.8.0-41-g348b7f5'}`

**To Reproduce**

1. Install Mainsail OS through the Raspberry pi imager
2. emptying the ~/printer_data/config folder 
3. using the git-method for retrieving and installing the SV06-plus configuration
4. determin the path of my printer and adding a line that in the printer.cfg of the MCU
5. doing a FIRMWARE_RESTART

**Expected behavior**
Mainsail screen opens without an error

**Screenshots**

**What printer are you using?**
SV06 Plus

**What kind of device are you using to host Klipper?**
Raspberry pi 4 with 4Gb RAM
- OS: Mainsail OS
- Version: 1.2.1

**How did you install Klipper?**
Included in Mainsail OS, which was installed using Raspberry pi Imager

- Manual install, KIAUH, MainsailOS, FluiddPi, etc.
None

**Is your local copy of this configuration up to date?**
My suspicion is that Mainsail OS comes with an older version of Klipper, where  =axis_twist_compensation= is not yet implemented

- This configuration changes all the time, when did you install it? Are you sure you're running the latest version?
This evening I installed everything

**What slicer are you using?**
- [ ] OrcaSlicer

**Are you using the config bundles from this repo?**
- [ ] Yes

**Did you [Adjust your slicer](https://github.com/bassamanator/Sovol-SV06-firmware#adjust-your-slicer)**?
Not relevant

**Additional context**
My suspicion is that Mainsail OS comes with an older version of Klipper, where  =axis_twist_compensation= is not yet implemented.
When I install KIAUH it says that version 0.11.0-205 of Klipper is installed, while 0.12.0-10 is the latest. Mainsail is version 2.5.1 while 2.8.0 is the latest. Moonraker is almost up to date.

After an update of Klipper, Mainsail and Moonraker through KIAUH everything works as expected.

So please add in the README.md after "Klipper must be installed on the host Raspberry Pi for everything to work. Easiest is to use a [MainsailOS](https://github.com/mainsail-crew/mainsail/releases/latest) image. Alternatively, you can install Fluidd or Mainsail via [KIAUH](https://github.com/th33xitus/kiauh)." that once needs to update MainsailOS through KIAUH

**Comment by bassamanator** [comment]
Readme adjusted. Thanks.

**Comment by Trilis29** [comment]
I don't see anything in readme about compensation
