### ISSUE TITLE
[BUG] Homing in heated chamber sometimes causes false endstop trigger

### ISSUE THREAD

**Issue by GTreaper** [bassamanator/Sovol-SV06-firmware#140]
**Describe the bug**
After doing alot of printing inside a heated chamber printing ASA I stumbled upon a small hick up. 
While homing it sometimes didn't move the X and Y axis(bed and tool head) all the way but triggered endstop causing it to move bed forward until it couldn't move anymore and continue to try moving it. 

**To Reproduce**
Heat chamber to roughly 38c and up 

**Expected behavior**
Home like it should 

**What printer are you using?**

- SV06 Plus

**What kind of device are you using to host Klipper?
Pi 4

**Additional context**
To fix I lowered the value driver_SGTHRS in printer.cfg with - 2 on XY so far it hasn't happened but it's not a consistent issue.
It might need to be lowered more.

Wanted to post this incase any new user experience this issue. This could also happen if just the bed or tool head carriage are a bit to tight.
Repo owner may close this straight away if he doesn't feel like adding a note or two this was just intended for future users fault searching.

:)

**Comment by bassamanator** [comment]
This is the nature of sensorless homing, the user might need to adjust related settings to have it work best with their unit, and, or, in their print environment.

Best.
