### ISSUE TITLE
Add a mcu temperature sensor section

### ISSUE THREAD

**Issue by graccoon** [bassamanator/Sovol-SV06-firmware#141]
Fortunately, stm32 has an internal temperature sensor, which allows you to track frequent errors with its overheating (don't forget that in the standard configuration the MCU cooling fan is connected to the model cooling fan). In particular, the famous "timer too close" error has been haunting me for the last couple of weeks, and thanks to working with cooling and temperature tracking it was possible to eliminate MCU overheating.
And the proposed section is very simple:
```
[temperature_sensor mcu_temp].
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100
```

**Comment by graccoon** [comment]
I've found source of my code block:
https://klipper.discourse.group/t/stm32h743xx-mcu-temperature/5867/2

**Comment by bassamanator** [comment]
This is nothing new; feel free to look through closed issues on this. The reason this section was *removed* from this config was because it doesn't play nicely with this motherboard. 

It's very likely your issues are related to having added this section.
