### ISSUE TITLE
[BUG] Layer shifting occurs at stock or near stock Klipper configs

### ISSUE THREAD

**Issue by LimesKey** [bassamanator/Sovol-SV06-firmware#150]
With the stock Klipper configs in this repository with 3000 Max Accel and 200 Max Velocity, I get severe layer shifting on my Sovol SV06.

![IMG_0960](https://github.com/bassamanator/Sovol-SV06-firmware/assets/85136735/5bc6f2b8-6c19-4467-8e2f-4cbbcc0d2338)
This image was taken a few weeks ago and this is the most severe it has ever been, but usually it's a little better than this.

I have 2 SV06s both running Klipper on the same Raspberry Pi 4 4GB, layer shifting occurs on both on all axes except the Z (and extruder) I think. Even after increasing the X and Y motor currents by ~0.2 amps it still occurs, only after turning down the acceleration and velocity to 2000 and 100 respectively, does it cease.

I have not done any input shaping but I have made sure the rails and axes are well lubricated and that the bed cabling does not get caught or anything. Below are my printer configs for both printers.

[Cosmo-Printer.cfg.txt](https://github.com/bassamanator/Sovol-SV06-firmware/files/14337224/Cosmo-Printer.cfg.txt)
[Pepper-Printer.cfg.txt](https://github.com/bassamanator/Sovol-SV06-firmware/files/14337223/Pepper-Printer.cfg.txt)

**Comment by bassamanator** [comment]
These limits are set to reasonable amounts. You are the first user mentioning this issue. I would suggest you check the initial steps section in the everything-sv06 repo.
