### ISSUE TITLE
Moonraker can't connect to Klipper

### ISSUE THREAD

**Issue by HemlockMimosa** [bassamanator/Sovol-SV06-firmware#17]
### Discussed in https://github.com/bassamanator/Sovol-SV06-firmware/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **HemlockMimosa** March 21, 2023</sup>
Hi folks! Wondering if you can help me.

I installed Klipper on my Pi using KIAUH, then followed instructions for flashing Klipper onto the SV06, all of which seem to have worked. 

sudo service klipper status returns the following:

klipper.service - Klipper 3D Printer Firmware SV1
     Loaded: loaded (/etc/systemd/system/klipper.service; enabled; vendor prese>
     Active: active (running) since Wed 2023-03-22 01:15:53 GMT; 9min ago
       Docs: https://www.klipper3d.org/
   Main PID: 965 (python)
      Tasks: 2 (limit: 3933)
        CPU: 1.690s
     CGroup: /system.slice/klipper.service
             └─965 /home/andre/klippy-env/bin/python /home/andre/klipper/klippy>

Mar 22 01:15:53 raspberrypi systemd[1]: Started Klipper 3D Printer Firmware SV1.
lines 1-11/11 (END)
● klipper.service - Klipper 3D Printer Firmware SV1
     Loaded: loaded (/etc/systemd/system/klipper.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-03-22 01:15:53 GMT; 9min ago
       Docs: https://www.klipper3d.org/
   Main PID: 965 (python)
      Tasks: 2 (limit: 3933)
        CPU: 1.690s
     CGroup: /system.slice/klipper.service
             └─965 /home/andre/klippy-env/bin/python /home/andre/klipper/klippy/klippy.py >

I _think_ this means that Klipper is successfully running on my printer, which means that the problem is occurring when I try to modify my configuration file.

ls -l /dev/serial/by-id/ returns the following: lrwxrwxrwx 1 root root 13 Mar 22 00:55 usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB0

I've attempted to modify my configuration file in Mainsail by adding either the entire string, "usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB0" or just "usb-1a86_USB_Serial-if00-port0"

None of these have worked. In addition, I've tried to perform the "make flash FLASH_DEVICE=/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0" only to learn that there is "No rule to make target 'flash'"

Do any of you have any troubleshooting advice, or is there any step I'm missing? Thanks for your advice and comments.</div>

**Comment by bassamanator** [comment]
Unrelated to this config.
