### ISSUE TITLE
Add SV06 High-speed firmware to the repo

### ISSUE THREAD

**Issue by apparle** [bassamanator/Sovol-SV06-firmware#183]
I like your git repo as a one-stop-shop for SV06. But you only have the old Marlin firmware, not the Sovol's latest high-speed Marlin firmware along with all the slicer config files on https://wiki.sovol3d.com/en/SV06 
```
SV06 Marlin High Speed：https://drive.google.com/drive/folders/1nOCIkOwC72kUQ6fCGt0dNmMTQbQu7B7k?usp=sharing
```
I've been using this firmware with OrcaSlicer config for last few months and it is working well.

**Comment by bassamanator** [comment]
Since I don't want to have to maintain a fresh copy of the marlin firmware on this repo, it's been deleted.

Thanks for the housekeeping reminder! 🙏🏻
