### ISSUE TITLE
Could not read from remote repository

### ISSUE THREAD

**Issue by 4q1** [bassamanator/Sovol-SV06-firmware#3]
pi@mainsail:~/printer_data/config $ git clone -b master --single-branch git@github.com:bassamanator/Sovol-SV06-firmware.git .
Cloning into '.'...
git@github.com: Permission denied (publickey).
**fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.

**Comment by bassamanator** [comment]
Hi there,

It's likely that you need to generate SSH keys and add them to your github account. See this [answer on stackoverflow](https://stackoverflow.com/a/31326085).

However, you can skip all that and just download the zip from the main page by clicking `Code`, `Download ZIP`, or just click [here](https://github.com/bassamanator/Sovol-SV06-firmware/archive/refs/heads/master.zip).

Let me know if that works.

**Comment by bassamanator** [comment]
Please see instructions [here](https://github.com/bassamanator/Sovol-SV06-firmware#download-the-zip).
