### ISSUE TITLE
MicroSD that comes with SV06 cannot flash the MCU with Klipper.bin

### ISSUE THREAD

**Issue by nickmmain** [bassamanator/Sovol-SV06-firmware#52]
I'd just like to report that I can confirm exactly the behavior that was reported in: 

https://github.com/bassamanator/Sovol-SV06-firmware/discussions/32

I lost a couple hours trying and re-trying to flash the SV06 with Klipper.bin. I had the exact same errors and debugging output.

The solution was also the same; I used a SanDisk 16GB micro SD card, formatted as directed in the Readme. Can, or should, it be mentioned in the readme to **not** use the SD card provided with the machine ?

**Comment by bassamanator** [comment]
Interestingly enough, I could *only flash* using the microSD card that came with the printer.

Are you able to flash Marlin using the Sovol sd card (Kingfast I believe)?

**Comment by JayKayUk** [comment]
I'll just jump in here and also confirm that the microSD card that came with the printer doesn't work for flashing for me. It worked once for Hill's version of Marlin, but after like 20 power cycles. Some time after that I wanted to flash Klipper, I couldn't flash it nor the 1.9.2 firmware, even after multiple power cycles. I had to buy the SanDisk 16 GB. It literally worked first try.

**Comment by bassamanator** [comment]
@JayKayUk Are you saying that you were able to flash Marlin with the Sovol sd card, but not Klipper?

**Comment by JayKayUk** [comment]
I'll walk you through what I've done with what: 

1. Got the SV06 printer and after some time updated to 2.0.0 with the stock SD card (Kingfast or whatever it is). It took a lot of power cycles and being afraid, I bricked the board.
2. After some time found Hill's updated version of Marlin with UBL and all. Again, flashed it with the stock card with maaaany power cycles.
3. After that, I got interested in Klipper, so I tried flashing it with the stock card. It didn't seem to work, so I thought I'd try to flash 1.9.2 fw. Didn't work either. Said screw it. Now the printer doesn't work at all.
4. Ordered the SanDisk 16 GB from Amazon. Flashed 1.9.2 fw first try. After I confirmed that the board is not bricked from me trying different files/names/power cycles, I tried flashing Klipper. Worked first try again.

**Comment by bassamanator** [comment]
@JayKayUk Very interesting. Let's see what @nickmmain has to tell us.

**Comment by corbt** [comment]
I'm also using the stock KingFast 8GB SD card and am unable to flash the Klipper firmware. The printer just gets stuck on a blank screen and never boots up.

I am able to flash the stock 2.0.0 firmware using the same card.

**Comment by bassamanator** [comment]
@corbt Thanks for the feedback. I'll add a warning to that section.
