### ISSUE TITLE
Firmware configuration

### ISSUE THREAD

**Issue by M0des1900** [bassamanator/Sovol-SV06-firmware#69]
![Screenshot_20230618_141717](https://github.com/bassamanator/Sovol-SV06-firmware/assets/136999906/898be73e-addb-4be7-b9ce-e8ac942bd433)
Hey,
I'm about to klipperize my sv06 plus. Can anyone help me, what I exatctly have to do at step 2? What command is it that for safety reasons isn't mentioned?

Thanks for your help

**Comment by bassamanator** [comment]
Instructions on how to delete files are clearly stated.

This is not an issue, feel free to create a discussion.
