### ISSUE TITLE
Draw Purge Line[BUG]

### ISSUE THREAD

**Issue by Chewyyy** [bassamanator/Sovol-SV06-firmware#76]
**Describe the bug**

**To Reproduce**
1. Start a Print
2. Print doesn't draw purge line
3. If you try and run draw_purge_line alone, it gives error "Error evaluating 'gcode_macro draw_purge_line:gcode': ZeroDivisionError: float division by zero"

**Expected behavior**
Drawing of a purge line before prints begin

**Screenshots**

**What kind of device are you using to host Klipper?**
 - RPi 4B, up to date as of 07/22/2023

**How did you install Klipper?**
 - Mainsail

**Additional context**
No other macros being run other than your package

**Comment by bassamanator** [comment]
There is no draw_purge_line macro included in this config. Please read about  purge_line macro in the docs.

**Comment by Chewyyy** [comment]
You are absolutely right and I am an idiot.  Sorry!!!
