### ISSUE TITLE
Add [z_tilt] config

### ISSUE THREAD

**Issue by chrisngobanh** [bassamanator/Sovol-SV06-firmware#80]
Just wondering why we have a [screws_tilt_adjust] but not a [z_tilt] config. Shouldn't it be the other way around for the SV06?

**Comment by bassamanator** [comment]
This printer has 2 z stepper motors connected to the same stepper driver, meaning that the motors cannot work independently of each other. So `z_tilt` doesn't help us.

`screws_tilt_adjust` allows those of us who have done the silicon spacer mod to fine tune the tilt, if any, of our beds.

**Comment by chrisngobanh** [comment]
Thanks for the info. I assumed that z_tilt was a manual process that I could use to adjust my lead screws, but I guess I could just create a separate macro for it.
